
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T19:15:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "de22c9c68337f1280ba884f93cf0910676277ee3",
 "version": "4.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
